server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: volunteer
          uri: http://localhost:8082
          predicates:
            - Path=/volunteerInfos/**, 
        - id: 매칭시스템
          uri: http://localhost:8083
          predicates:
            - Path=/matchingInfos/**, 
        - id: volunteering
          uri: http://localhost:8084
          predicates:
            - Path=/volunteerings/**, /checkVolunteeringApplicationHistories/**
        - id: 수혜기관
          uri: http://localhost:8085
          predicates:
            - Path=/associationInfos/**, /봉사활동정보/**, /봉사활동일정조회/**
        - id: community
          uri: http://localhost:8086
          predicates:
            - Path=/communities/**, 
        - id: mypage
          uri: http://localhost:8087
          predicates:
            - Path=, /myPages/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: volunteer
          uri: http://volunteer:8080
          predicates:
            - Path=/volunteerInfos/**, 
        - id: 매칭시스템
          uri: http://매칭시스템:8080
          predicates:
            - Path=/matchingInfos/**, 
        - id: volunteering
          uri: http://volunteering:8080
          predicates:
            - Path=/volunteerings/**, 
        - id: 수혜기관
          uri: http://수혜기관:8080
          predicates:
            - Path=/associationInfos/**, /봉사활동정보/**, 
        - id: community
          uri: http://community:8080
          predicates:
            - Path=/communities/**, 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
