---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer
  labels:
    app: volunteer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer
  template:
    metadata:
      labels:
        app: volunteer
    spec:
      containers:
        - name: volunteer
          image: username/volunteer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 매칭시스템
  labels:
    app: 매칭시스템
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 매칭시스템
  template:
    metadata:
      labels:
        app: 매칭시스템
    spec:
      containers:
        - name: 매칭시스템
          image: username/매칭시스템:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteering
  labels:
    app: volunteering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteering
  template:
    metadata:
      labels:
        app: volunteering
    spec:
      containers:
        - name: volunteering
          image: username/volunteering:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 수혜기관
  labels:
    app: 수혜기관
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 수혜기관
  template:
    metadata:
      labels:
        app: 수혜기관
    spec:
      containers:
        - name: 수혜기관
          image: username/수혜기관:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: community
  labels:
    app: community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community
  template:
    metadata:
      labels:
        app: community
    spec:
      containers:
        - name: community
          image: username/community:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      containers:
        - name: mypage
          image: username/mypage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: volunteer
  labels:
    app: volunteer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: volunteer


---


apiVersion: v1
kind: Service
metadata:
  name: 매칭시스템
  labels:
    app: 매칭시스템
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 매칭시스템


---


apiVersion: v1
kind: Service
metadata:
  name: volunteering
  labels:
    app: volunteering
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: volunteering


---


apiVersion: v1
kind: Service
metadata:
  name: 수혜기관
  labels:
    app: 수혜기관
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 수혜기관


---


apiVersion: v1
kind: Service
metadata:
  name: community
  labels:
    app: community
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: community


---


apiVersion: v1
kind: Service
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mypage

